app/account/urls.py
from django.urls import path
from account.views import UserRegisterView, UserLoginView, UserLogoutView


app_name = 'account'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('cheque.urls')),
    path('', include('account.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/cheque/urls.py
from django.urls import path
from cheque.views import RegularizacaoCreateView

app_name = 'cheque'

urlpatterns = [
    path('regularizacao/create', RegularizacaoCreateView.as_view(), name='regularizacao-create'),
]

app/core/urls.py
from django.urls import path
from core.views import IndexView, EmitenteCreateView, ChequeCreateView, EmitenteListView, EmitenteUpdateView, \
                       GenerateEmitentePDF, TodosChequesListView, GenerateChequePDF, ChequeCanceladoListView, \
                       GenerateChequeCanceladoPDF, ChequeRegularizadoListView, GenerateChequeRegularizadoPDF
from core import views


app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('emitente/create/', EmitenteCreateView.as_view(), name='emitente-create'),
    path('emitente/', EmitenteListView.as_view(), name='emitente'),
    path('emitente/<int:pk>', EmitenteUpdateView.as_view(), name='emitente-edit'),
    path('cheque/create/', ChequeCreateView.as_view(), name='cheque-create'),
    path('cheque/', TodosChequesListView.as_view(), name='cheque'),
    path('cheque/cancelado/', ChequeCanceladoListView.as_view(), name='cheque-cancelado'),
    path('cheque/relatorio/', GenerateChequePDF.as_view(), name='cheque-relatorio'),
    path('cheque/regularizado/', ChequeRegularizadoListView.as_view(), name='cheque-regularizado'),
    path('cheque-regularizado/relatorio/', GenerateChequeRegularizadoPDF.as_view(), name='cheque-regularizado-relatorio'),
    path('cheque-cancelado/relatorio/', GenerateChequeCanceladoPDF.as_view(), name='cheque-cancelado-relatorio'),
    path('celery/', views.celery, name='celery'),
    path('emitente/relatorio', GenerateEmitentePDF.as_view(), name='emitente-relatorio'),
    # path('emitente/create', views.EmitenteCreateView, name='emitente'),
   ]

app/core/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.urls import reverse
from django.db.models.signals import pre_save, post_save

from PIL import Image

from core.utils import regularizacao_file_path, user_image_path


ESTADO_CHEQUE = (
    ('Devolvido', 'Devolvido'),
    ('Cancelado', 'Cancelado'),
    ('Regularizado', 'Regularizado')
)

TIPO_EMITENTE = (
    ('P', 'Particular'), 
    ('E', 'Empresa')
)

FORMA_REGULARIZACAO = (
    ('Cheque', 'Cheque'),
    ('Numerario', 'Numerario')
)

class Banco(models.Model):
    nome = models.CharField(max_length=100, unique=True)


    def __str__(self):
        return self.nome


class MotivoDevolucao(models.Model):
    codigo = models.IntegerField(default=11, unique=True)
    descricao = models.CharField(max_length=255, unique=True)


    def __str__(self):
        return self.descricao

    class Meta:
        verbose_name = 'Motivo de Devolucao'
        verbose_name_plural = 'Motivos de Devolucao'


class Assinante(models.Model):
    nome = models.CharField(max_length=255)
    numero_conta = models.CharField(max_length=100, unique=True)
    telefone_1 = models.CharField(max_length=50, unique=True)
    telefone_2 = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    endereco = models.CharField(max_length=255)
    bloqueio_utr = models.BooleanField(default=False)

    def __str__(self):
        return self.nome

class Emitente(models.Model):
    nome = models.CharField(max_length=255)
    numero_conta = models.CharField(max_length=100, unique=True)
    telefone_1 = models.CharField(max_length=50, unique=True)
    telefone_2 = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    endereco = models.CharField(max_length=255)
    tipo = models.CharField(max_length=1, choices=TIPO_EMITENTE)
    assinante = models.ManyToManyField(Assinante, blank=True)
    bloqueio_utr = models.BooleanField(default=False)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('core:emitente')


class Cheque(models.Model):
    motivo_devolucao = models.ForeignKey(MotivoDevolucao, on_delete=models.CASCADE)
    numero_cheque = models.CharField(max_length=50, unique=True)
    emitente = models.ForeignKey(Emitente, on_delete=models.CASCADE)
    numero_conta = models.CharField(max_length=100, unique=True)
    valor_cheque = models.DecimalField(max_digits=10, decimal_places=2)
    data_devolucao = models.DateTimeField(null=True, blank=True)
    codigo_balcao = models.CharField(max_length=100)
    estado_cheque = models.CharField(max_length=50, choices=ESTADO_CHEQUE, default='Devolvido')
    banco = models.ForeignKey(Banco, on_delete=models.CASCADE)
    data_criacao = models.DateTimeField(auto_now_add=True)
    dias = models.IntegerField(default=0)

    def __str__(self):
        return self.numero_cheque

class Regularizacao(models.Model):
    forma = models.CharField(max_length=10, choices=FORMA_REGULARIZACAO)
    cheque = models.ForeignKey(Cheque, on_delete=models.CASCADE)
    file = models.FileField(upload_to=regularizacao_file_path, null=True, blank=True)


    def __str__(self):
        return self.cheque.numero_cheque

    class Meta:
        verbose_name_plural = 'Regularizacoes'

def update_estado_cheque(sender, instance, created, *args, **kwargs):
    if created:
        cheque = Cheque.objects.get(regularizacao=instance)
        cheque.estado_cheque = 'Regularizado'
        cheque.save()
       

post_save.connect(update_estado_cheque, sender=Regularizacao)


class UserManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        """Creates and saves a new user"""
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password):
        """Creates and saves a new super user"""
        user = self.create_user(email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model that suppors using email instead of username"""
    email = models.EmailField(max_length=255, unique=True)
    nome = models.CharField(max_length=255, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name="profile")
    image = models.ImageField(upload_to=user_image_path, default="uploads/documentos/default_user.png")
   
    def __str__(self):
        return self.user.email

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


    def save(self, *args,**kwargs):
        super(Profile, self).save(*args,**kwargs)
        img = Image.open(self.image)
        if img.height > 200 or img.width > 200 :
            new_size = (200,200)
            img.thumbnail(new_size)
            img.save(self.image.path)

def post_save_user_signal(sender, instance, created, *args, **kwargs):
    if created:
        profile = Profile.objects.create(user=instance)
        profile.save()

post_save.connect(post_save_user_signal, sender=User)

app/core/forms.py
from django import forms
from django.utils.translation import ugettext as _

from core.models import Emitente, Cheque

class EmitenteForm(forms.ModelForm):
    class Meta:
        model = Emitente
        fields = ( 'nome', 'numero_conta', 'telefone_1', 'telefone_2', 'email', 'endereco', 'tipo', 'assinante',)
        
        label = {
            'nome': _('Nome'),           
            'numero_conta': _('Numero da Conta'),
            'telefone_1': _('Telefone Principal'),
            'telefone_2': _('Telefone Secundario'),
            'email': _('Email'),
            'endereco': _('Endereco'),
            'tipo': _('Tipo Emitente'),
            'assinante': _('Assinante'),
        }


class ChequeForm(forms.ModelForm):

    class Meta:
        model = Cheque
        fields = ('motivo_devolucao', 'numero_cheque', 'banco', 'emitente', 'numero_conta',
                  'valor_cheque', 'data_devolucao', 'codigo_balcao')

        # widgets = {
        #     'motivo_devolucao': forms.Select(attrs={'class': 'form-control'}),
        #     'numero_cheque': forms.TextInput(attrs={'class': 'form-control'}),
        #     'banco': forms.Select(attrs={'class': 'form-control'}),
        #     'emitente': forms.Select(attrs={'class': 'form-control'}),
        #     'numero_conta': forms.TextInput(attrs={'class': 'form-control'}),
        #     'valor_cheque': forms.TextInput(attrs={'class': 'form-control'}),
        #     'data_devolucao': forms.DateInput(attrs={'class': 'form-control datepicker'}),
        #     'codigo_balcao': forms.TextInput(attrs={'class': 'form-control'})
        # }

        label = {
            'motivo_devolucao': _('Motivo Devolucao'),
            'numero_cheque': _('Numero Cheque'),
            'emitente': _('Emitente'),
            'banco': _('Banco'),
            'numero_conta': _('Numero Conta'),
            'valor_cheque': _('Valor Cheque'),
            'data_devolucao': _('Data Devolucao'),
            'codigo_balcao': _('Codigo Balcao'),
            'estado_cheque': _('Estado Cheque')
        }

app/core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.views.generic import TemplateView, ListView, CreateView, UpdateView, View

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.utils import timezone

from core.forms import EmitenteForm, ChequeForm

from core.models import Banco, Emitente, Cheque, Profile, User

from core.utils import render_to_pdf
from django.template.loader import get_template

from core.tasks import send_report, update_dias, update_status_cheque, bloqueio_conta

@method_decorator(login_required(login_url='account:login'), name='dispatch')
class IndexView(ListView):
    template_name = 'index.html'
    context_object_name = 'cheque_list'
    model = Cheque

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['cheque_devolvido'] = Cheque.objects.all().count()
        context['cheque_cancelado'] = Cheque.objects.filter(estado_cheque='Cancelado').count()
        context['cheque_regularizado'] = Cheque.objects.filter(estado_cheque='Regularizado').count()

        return context

    def get_queryset(self):
        return Cheque.objects.all()




@method_decorator(login_required(login_url='account:login'), name='dispatch')
class EmitenteCreateView(SuccessMessageMixin, CreateView):
    template_name = 'emitente_create.html'
    form_class = EmitenteForm
    success_url = '/'
    success_message = 'Emitente adicionado com sucesso!'

    def form_valid(self, form):
        emitente = form.save(commit=False)
        emitente.save()
        return redirect(self.success_url)


@method_decorator(login_required(login_url='account:login'), name='dispatch')
class EmitenteListView(ListView):
    template_name = 'emitente_list.html'
    queryset = Emitente.objects.all()
    paginate_by = 5


@method_decorator(login_required(login_url='account:login'), name='dispatch')
class EmitenteUpdateView(UpdateView):
    model = Emitente
    fields = ['nome', 'numero_conta', 'telefone_1', 'telefone_2', 'email', 'endereco', 'tipo', 'assinante']


@method_decorator(login_required(login_url='account:login'), name='dispatch')
class ChequeCreateView(SuccessMessageMixin, CreateView):
    template_name = 'cheque_create.html'
    form_class = ChequeForm
    success_url = '/'
    success_message = 'Chque adicionado com sucesso'

    def form_valid(self, form):
        cheque = form.save(commit=False)
        cheque.estado_cheque = 'Devolvido'
        cheque.save()
        return redirect(self.success_url)



@method_decorator(login_required(login_url='account:login'), name='dispatch')
class TodosChequesListView(ListView):
    template_name = 'cheque_list.html'
    queryset = Cheque.objects.all()


@method_decorator(login_required(login_url='account:login'), name='dispatch')
class ChequeCanceladoListView(ListView):
    template_name = 'cheque_cancelado_list.html'
    queryset = Cheque.objects.filter(estado_cheque='Cancelado')



@method_decorator(login_required(login_url='account:login'), name='dispatch')
class ChequeRegularizadoListView(ListView):
    template_name = 'cheque_regularizado_list.html'
    queryset = Cheque.objects.filter(estado_cheque='Regularizado')

def celery(request):
    update_dias.delay()
    update_status_cheque.delay()
    bloqueio_conta.delay()
    return HttpResponse('Enviado com sucesso')


@method_decorator(login_required(login_url='account:login'), name='dispatch')

class GenerateEmitentePDF(View):
    def get(self, request, *args, **kwargs):
        template = get_template('reports/emitente.html')
        queryset = Emitente.objects.all()
        context = {
            "queryset": queryset,
            "data": timezone.now()
        }
        html = template.render(context)
        pdf = render_to_pdf('reports/emitente.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Clientes_%s.pdf" %("12341231")
            content = "inline; filename='%s'" %(filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" %(filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")


@method_decorator(login_required(login_url='account:login'), name='dispatch')
class GenerateChequePDF(View):
    def get(self, request, *args, **kwargs):
        template = get_template('reports/cheque.html')
        queryset = Cheque.objects.all()
        context = {
            "queryset": queryset,
            "data": timezone.now()
        }
        html = template.render(context)
        pdf = render_to_pdf('reports/cheque.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Cheques_%s.pdf" %("12341231")
            content = "inline; filename='%s'" %(filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" %(filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")


@method_decorator(login_required(login_url='account:login'), name='dispatch')
class GenerateChequeCanceladoPDF(View):
    def get(self, request, *args, **kwargs):
        template = get_template('reports/cheque-cancelado.html')
        queryset = Cheque.objects.filter(estado_cheque='Cancelado')
        context = {
            "queryset": queryset,
            "data": timezone.now()
        }
        html = template.render(context)
        pdf = render_to_pdf('reports/cheque-cancelado.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Cheques_%s.pdf" %("12341231")
            content = "inline; filename='%s'" %(filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" %(filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")


@method_decorator(login_required(login_url='account:login'), name='dispatch')
class GenerateChequeRegularizadoPDF(View):
    def get(self, request, *args, **kwargs):
        template = get_template('reports/cheque-regularizado.html')
        queryset = Cheque.objects.filter(estado_cheque='Regularizado')
        context = {
            "queryset": queryset,
            "data": timezone.now()
        }
        html = template.render(context)
        pdf = render_to_pdf('reports/cheque-regularizado.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Cheques_%s.pdf" %("12341231")
            content = "inline; filename='%s'" %(filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" %(filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")

app/core/templates/layouts/base.html
<!DOCTYPE HTML>
<html>
<head>
{% load static %}
<title>{% block title %}SIGC{% endblock title %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content=SIGC" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="{% static 'css/bootstrap.min.css' %}" rel='stylesheet' type='text/css' />
<!-- Custom CSS -->
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
<!-- Graph CSS -->
<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
<!-- jQuery -->
<link href='//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400' rel='stylesheet' type='text/css'>
<!-- lined-icons -->
<link rel="stylesheet" href="{% static 'css/icon-font.min.css' %}" type='text/css' />
<!-- //lined-icons -->
<script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
<script src="{% static 'js/amcharts.js' %}"></script>	
<script src="{% static 'js/serial.js' %}"></script>	
<script src="{% static 'js/light.js' %}"></script>	
<script src="{% static 'js/radar.js' %}"></script>	
<link href="{% static 'css/barChart.css' %}" rel='stylesheet' type='text/css' />
<link href="{% static 'css/fabochart.css' %}" rel='stylesheet' type='text/css' />
<!-- Date Time Picker CSS -->
  <link rel="stylesheet" href="{% static 'date-time-phone/jquery-ui.css' %}">
  <link rel='stylesheet' href="{% static 'date-time-phone/jquery-ui-timepicker-addon.css' %}" />
<!-- Date Time Picker CSS -->

<!--clock init-->
<script src="{% static 'js/css3clock.js' %}"></script>
<!--Easy Pie Chart-->
<!--skycons-icons-->
<script src="{% static 'js/skycons.js' %}"></script>

 <!-- Date Time Picker JS -->
  <script src="{% static 'date-time-phone/jquery-ui.js' %}" ></script>
  <script src="{% static 'date-time-phone/jquery-ui-timepicker-addon.js' %}"></script> 

<script src="{% static 'js/jquery.easydropdown.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>



<!--//skycons-icons-->
</head> 
<body>
<div class="page-container">
<!--/content-inner-->
<div class="left-content">
	<div class="inner-content">
	<!-- header-starts -->
	<div class="header-section">
				<!--menu-right-->
				<div class="top_menu">
						<div class="main-search">
									<form>
										<input type="text" value="Search" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = 'Search';}" class="text"/>
										<input type="submit" value="">
									</form>
							<div class="close"><img src="{% static 'images/cross.png"' %}" /></div>
						</div>
							<div class="srch"><button></button></div>
							<script type="text/javascript">
									$('.main-search').hide();
								$('button').click(function (){
									$('.main-search').show();
									$('.main-search text').focus();
								}
								);
								$('.close').click(function(){
									$('.main-search').hide();
								});
							</script>
					<!--/profile_details-->
						<div class="profile_details_left">
							<ul class="nofitications-dropdown">
									<li class="dropdown note">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope-o"></i> <span class="badge">3</span></a>
									</li>

										
								
					<li class="dropdown note">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-bell-o"></i> <span class="badge">5</span></a>

					</li>	
				<li class="dropdown note">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-tasks"></i> <span class="badge blue1">9</span></a>
								
					</li>		   							   		
					<div class="clearfix"></div>	
						</ul>
					</div>
					<div class="clearfix"></div>	
					<!--//profile_details-->
				</div>
				<!--//menu-right-->
			<div class="clearfix"></div>
		</div>
			
	{% block content %}
	{% endblock content %}
										
	<footer>
		<p>&copy 2020 Fincode Lda. All Rights Reserved</a></p>
	</footer>
<!--footer section end-->
    </div>
</div>
				<!--//content-inner-->
			<!--/sidebar-menu-->
				<div class="sidebar-menu">
					<header class="logo">
					<a href="#" class="sidebar-icon"> <span class="fa fa-bars"></span> </a> <a href="{% url 'core:index' %}"> <span id="logo"> <h1>SIGC</h1></span> 
					<!--<img id="logo" src="" alt="Logo"/>--> 
				  </a> 
				</header>
<div style="border-top:1px solid rgba(69, 74, 84, 0.7)"></div>
<!--/down-->
				<div class="down">	
							<a href="index.html"><img src={{request.profile.imageURL}}></a>
							<a href="index.html"><span class=" name-caret">{{request.user.nome}}</span></a>
							<p></p>
						<ul>
						<li><a class="tooltips" href="index.html"><span>Perfil</span><i class="lnr lnr-user"></i></a></li>
							<li><a class="tooltips" href="index.html"><span>Definicoes</span><i class="lnr lnr-cog"></i></a></li>
							<li><a class="tooltips" href="{% url 'account:login' %}"><span>Sair</span><i class="lnr lnr-power-switch"></i></a></li>
							</ul>
						</div>
					<!--//down-->
				<div class="menu">
						<ul id="menu" >
							
								<li id="menu-academico" ><a href="#"><i class="fa fa-file-text-o"></i> <span>Cadastro</span> <span class="fa fa-angle-right" style="float: right"></span></a>
									<ul id="menu-academico-sub" >
									<li id="menu-academico-boletim" ><a href="{% url 'core:emitente-create' %}">Clientes</a></li>
									</ul>
								</li>
						
						<li id="menu-academico" ><a href="#"><i class="lnr lnr-book"></i> <span>Cheques</span> <span class="fa fa-angle-right" style="float: right"></span></a>
								<ul id="menu-academico-sub" >
								<li id="menu-academico-avaliacoes" ><a href="{% url 'core:cheque-create' %}">Registar</a></li>
					
								</ul>
							</li>
							
						<li id="menu-academico" ><a href="#"><i class="lnr lnr-layers"></i> <span>Regularização</span> <span class="fa fa-angle-right" style="float: right"></span></a>
								<ul id="menu-academico-sub" >
								<li id="menu-academico-avaliacoes" ><a href="{% url 'cheque:regularizacao-create' %}">Registar</a></li>

								</ul>
							</li>
						<li><a href="chart.html"><i class="lnr lnr-chart-bars"></i> <span>Relatórios</span> <span class="fa fa-angle-right" style="float: right"></span></a>
							<ul>
							<li><a href="{% url 'core:emitente' %}"><i class="lnr lnr-map"></i>Clientes</a></li>
							<li><a href="{% url 'core:cheque' %}"><i class="lnr lnr-map"></i>Cheques Devolvidos</a></li>
							<li><a href="{% url 'core:cheque-cancelado' %}"><i class="lnr lnr-apartment"></i>Cheques Cancelados</a></li>
							<li><a href="{% url 'core:cheque-regularizado' %}"><i class="lnr lnr-apartment"></i>Cheques Regularizados</a></li>
						</ul>
						</li>
						<li id="menu-comunicacao" ><a href="#"><i class="fa fa-smile-o"></i> <span>Mais</span><span class="fa fa-angle-double-right" style="float: right"></span></a>
							<ul id="menu-comunicacao-sub" >
							<li id="menu-mensagens" style="width:120px" ><a href="project.html">Mais <i class="fa fa-angle-right" style="float: right; margin-right: -8px; margin-top: 2px;"></i></a>
								<ul id="menu-mensagens-sub" >
								<li id="menu-mensagens-enviadas" style="width:130px" ><a href="ribbon.html">R</a></li>
								<li id="menu-mensagens-recebidas"  style="width:130px"><a href="blank.html">B</a></li>
								</ul>
							</li>
							<li id="menu-arquivos" ><a href="500.html">500</a></li>
							</ul>
						</li>
						</ul>
					</div>
					</div>
					<div class="clearfix"></div>		
				</div>
				<script>
				var toggle = true;
							
				$(".sidebar-icon").click(function() {                
					if (toggle)
					{
					$(".page-container").addClass("sidebar-collapsed").removeClass("sidebar-collapsed-back");
					$("#menu span").css({"position":"absolute"});
					}
					else
					{
					$(".page-container").removeClass("sidebar-collapsed").addClass("sidebar-collapsed-back");
					setTimeout(function() {
						$("#menu span").css({"position":"relative"});
					}, 400);
					}
								
								toggle = !toggle;
							});

<!--js -->
<link rel="stylesheet" href="css/vroom.css">
<script type="text/javascript" src="js/vroom.js"></script>
<script type="text/javascript" src="js/TweenLite.min.js"></script>
<script type="text/javascript" src="js/CSSPlugin.min.js"></script>
<script src="js/jquery.nicescroll.js"></script>
<script src="js/scripts.js"></script>
<script type="text/javascript" src="js/tipo.js"></script>

<!-- Bootstrap Core JavaScript -->
   <script src="js/bootstrap.min.js"></script>

<script>
    $( function() {
       {% comment %}  // $( "#id_birth_date" ).datetimepicker({ dateFormat: 'yy-mm-dd', maxDate: 0, controlType: 'select'}).attr("autocomplete", "off") ;
        // $( "#id_birth_date" ).timepicker({ dateFormat: 'yy-mm-dd', maxDate: 0, controlType: 'select'}).attr("autocomplete", "off") ; {% endcomment %}
        $( "#id_data_devolucao" ).datepicker({ dateFormat: 'dd-mm-yy' }).attr("autocomplete", "off") ;
    });
  </script>
  <!-- Date Time Picker JS -->

  <!-- Phone Mask JS -->
  <script src="{% static 'date-time-phone/jquery-input-mask-phone-number.min.js' %}"></script> 

  <script>
    //(xxx) xxx-xxxx format code
    $(document).ready(function () {
        $('#id_telefone_1').usPhoneFormat({
            format: '(xxx) xx-xxxxxxx',
        });   
    });
  </script>
  <!-- Phone Mask JS -->

</body>
</html>

app/core/templates/layouts/footer.html
<!--footer section start-->
<footer>
    <p>&copy 2020 Fincode . Todos os direitos reservados | Desenvolvido pela Fincode</p>
</footer>
<!--footer section end-->