app/account/urls.py
from django.urls import path
from account.views import UserRegisterView, UserLoginView, UserLogoutView


app_name = 'account'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('cheque.urls')),
    path('', include('account.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/urls.py
from django.urls import path
from core.views import IndexView, EmitenteCreateView, ChequeCreateView, EmitenteListView, EmitenteUpdateView, \
                       GenerateEmitentePDF, TodosChequesListView, GenerateChequePDF, ChequeCanceladoListView, \
                       GenerateChequeCanceladoPDF, ChequeRegularizadoListView, GenerateChequeRegularizadoPDF
from core import views


app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('emitente/create/', EmitenteCreateView.as_view(), name='emitente-create'),
    path('emitente/', EmitenteListView.as_view(), name='emitente'),
    path('emitente/<int:pk>', EmitenteUpdateView.as_view(), name='emitente-edit'),
    path('cheque/create/', ChequeCreateView.as_view(), name='cheque-create'),
    path('cheque/', TodosChequesListView.as_view(), name='cheque'),
    path('cheque/cancelado/', ChequeCanceladoListView.as_view(), name='cheque-cancelado'),
    path('cheque/relatorio/', GenerateChequePDF.as_view(), name='cheque-relatorio'),
    path('cheque/regularizado/', ChequeRegularizadoListView.as_view(), name='cheque-regularizado'),
    path('cheque-regularizado/relatorio/', GenerateChequeRegularizadoPDF.as_view(), name='cheque-regularizado-relatorio'),
    path('cheque-cancelado/relatorio/', GenerateChequeCanceladoPDF.as_view(), name='cheque-cancelado-relatorio'),
    path('celery/', views.celery, name='celery'),
    path('emitente/relatorio', GenerateEmitentePDF.as_view(), name='emitente-relatorio'),
    # path('emitente/create', views.EmitenteCreateView, name='emitente'),
   ]

app/core/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.urls import reverse
from django.db.models.signals import pre_save, post_save

from PIL import Image

from core.utils import regularizacao_file_path, user_image_path


ESTADO_CHEQUE = (
    ('Devolvido', 'Devolvido'),
    ('Cancelado', 'Cancelado'),
    ('Regularizado', 'Regularizado')
)

TIPO_EMITENTE = (
    ('P', 'Particular'), 
    ('E', 'Empresa')
)

FORMA_REGULARIZACAO = (
    ('Cheque', 'Cheque'),
    ('Numerario', 'Numerario')
)

class Banco(models.Model):
    nome = models.CharField(max_length=100, unique=True)


    def __str__(self):
        return self.nome


class MotivoDevolucao(models.Model):
    codigo = models.IntegerField(default=11, unique=True)
    descricao = models.CharField(max_length=255, unique=True)


    def __str__(self):
        return self.descricao

    class Meta:
        verbose_name = 'Motivo de Devolucao'
        verbose_name_plural = 'Motivos de Devolucao'


class Assinante(models.Model):
    nome = models.CharField(max_length=255)
    numero_conta = models.CharField(max_length=100, unique=True)
    telefone_1 = models.CharField(max_length=50, unique=True)
    telefone_2 = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    endereco = models.CharField(max_length=255)
    bloqueio_utr = models.BooleanField(default=False)

    def __str__(self):
        return self.nome

class Emitente(models.Model):
    nome = models.CharField(max_length=255)
    numero_conta = models.CharField(max_length=100, unique=True)
    telefone_1 = models.CharField(max_length=50, unique=True)
    telefone_2 = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    endereco = models.CharField(max_length=255)
    tipo = models.CharField(max_length=1, choices=TIPO_EMITENTE)
    assinante = models.ManyToManyField(Assinante, blank=True)
    bloqueio_utr = models.BooleanField(default=False)

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('core:emitente')


class Cheque(models.Model):
    motivo_devolucao = models.ForeignKey(MotivoDevolucao, on_delete=models.CASCADE)
    numero_cheque = models.CharField(max_length=50, unique=True)
    emitente = models.ForeignKey(Emitente, on_delete=models.CASCADE)
    numero_conta = models.CharField(max_length=100, unique=True)
    valor_cheque = models.DecimalField(max_digits=10, decimal_places=2)
    data_devolucao = models.DateTimeField(null=True, blank=True)
    codigo_balcao = models.CharField(max_length=100)
    estado_cheque = models.CharField(max_length=50, choices=ESTADO_CHEQUE, default='Devolvido')
    banco = models.ForeignKey(Banco, on_delete=models.CASCADE)
    data_criacao = models.DateTimeField(auto_now_add=True)
    dias = models.IntegerField(default=0)

    def __str__(self):
        return self.numero_cheque

class Regularizacao(models.Model):
    forma = models.CharField(max_length=10, choices=FORMA_REGULARIZACAO)
    cheque = models.ForeignKey(Cheque, on_delete=models.CASCADE)
    file = models.FileField(upload_to=regularizacao_file_path, null=True, blank=True)


    def __str__(self):
        return self.cheque.numero_cheque

    class Meta:
        verbose_name_plural = 'Regularizacoes'

def update_estado_cheque(sender, instance, created, *args, **kwargs):
    if created:
        cheque = Cheque.objects.get(regularizacao=instance)
        cheque.estado_cheque = 'Regularizado'
        cheque.save()
       

post_save.connect(update_estado_cheque, sender=Regularizacao)


class UserManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        """Creates and saves a new user"""
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password):
        """Creates and saves a new super user"""
        user = self.create_user(email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model that suppors using email instead of username"""
    email = models.EmailField(max_length=255, unique=True)
    nome = models.CharField(max_length=255, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name="profile")
    image = models.ImageField(upload_to=user_image_path, default="uploads/documentos/default_user.png")
   
    def __str__(self):
        return self.user.email

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


    def save(self, *args,**kwargs):
        super(Profile, self).save(*args,**kwargs)
        img = Image.open(self.image)
        if img.height > 200 or img.width > 200 :
            new_size = (200,200)
            img.thumbnail(new_size)
            img.save(self.image.path)

def post_save_user_signal(sender, instance, created, *args, **kwargs):
    if created:
        profile = Profile.objects.create(user=instance)
        profile.save()

post_save.connect(post_save_user_signal, sender=User)

app/core/forms.py
from django import forms
from django.utils.translation import ugettext as _

from core.models import Emitente, Cheque

class EmitenteForm(forms.ModelForm):
    class Meta:
        model = Emitente
        fields = ( 'nome', 'numero_conta', 'telefone_1', 'telefone_2', 'email', 'endereco', 'tipo', 'assinante',)
        
        label = {
            'nome': _('Nome'),           
            'numero_conta': _('Numero da Conta'),
            'telefone_1': _('Telefone Principal'),
            'telefone_2': _('Telefone Secundario'),
            'email': _('Email'),
            'endereco': _('Endereco'),
            'tipo': _('Tipo Emitente'),
            'assinante': _('Assinante'),
        }


class ChequeForm(forms.ModelForm):

    class Meta:
        model = Cheque
        fields = ('motivo_devolucao', 'numero_cheque', 'banco', 'emitente', 'numero_conta',
                  'valor_cheque', 'data_devolucao', 'codigo_balcao')

        # widgets = {
        #     'motivo_devolucao': forms.Select(attrs={'class': 'form-control'}),
        #     'numero_cheque': forms.TextInput(attrs={'class': 'form-control'}),
        #     'banco': forms.Select(attrs={'class': 'form-control'}),
        #     'emitente': forms.Select(attrs={'class': 'form-control'}),
        #     'numero_conta': forms.TextInput(attrs={'class': 'form-control'}),
        #     'valor_cheque': forms.TextInput(attrs={'class': 'form-control'}),
        #     'data_devolucao': forms.DateInput(attrs={'class': 'form-control datepicker'}),
        #     'codigo_balcao': forms.TextInput(attrs={'class': 'form-control'})
        # }

        label = {
            'motivo_devolucao': _('Motivo Devolucao'),
            'numero_cheque': _('Numero Cheque'),
            'emitente': _('Emitente'),
            'banco': _('Banco'),
            'numero_conta': _('Numero Conta'),
            'valor_cheque': _('Valor Cheque'),
            'data_devolucao': _('Data Devolucao'),
            'codigo_balcao': _('Codigo Balcao'),
            'estado_cheque': _('Estado Cheque')
        }

app/core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.views.generic import TemplateView, ListView, CreateView, UpdateView, View

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.utils import timezone

from core.forms import EmitenteForm, ChequeForm

from core.models import Banco, Emitente, Cheque, Profile, User

from core.utils import render_to_pdf
from django.template.loader import get_template

from core.tasks import send_report, update_dias, update_status_cheque, bloqueio_conta

@method_decorator(login_required(login_url='account:login'), name='dispatch')
class IndexView(ListView):
    template_name = 'index.html'
    context_object_name = 'cheque_list'
    model = Cheque

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['cheque_devolvido'] = Cheque.objects.all().count()
        context['cheque_cancelado'] = Cheque.objects.filter(estado_cheque='Cancelado').count()
        context['cheque_regularizado'] = Cheque.objects.filter(estado_cheque='Regularizado').count()

        return context

    def get_queryset(self):
        return Cheque.objects.all()




@method_decorator(login_required(login_url='account:login'), name='dispatch')
class EmitenteCreateView(SuccessMessageMixin, CreateView):
    template_name = 'emitente_create.html'
    form_class = EmitenteForm
    success_url = '/'
    success_message = 'Emitente adicionado com sucesso!'

    def form_valid(self, form):
        emitente = form.save(commit=False)
        emitente.save()
        return redirect(self.success_url)


@method_decorator(login_required(login_url='account:login'), name='dispatch')
class EmitenteListView(ListView):
    template_name = 'emitente_list.html'
    queryset = Emitente.objects.all()
    paginate_by = 5


@method_decorator(login_required(login_url='account:login'), name='dispatch')
class EmitenteUpdateView(UpdateView):
    model = Emitente
    fields = ['nome', 'numero_conta', 'telefone_1', 'telefone_2', 'email', 'endereco', 'tipo', 'assinante']


@method_decorator(login_required(login_url='account:login'), name='dispatch')
class ChequeCreateView(SuccessMessageMixin, CreateView):
    template_name = 'cheque_create.html'
    form_class = ChequeForm
    success_url = '/'
    success_message = 'Chque adicionado com sucesso'

    def form_valid(self, form):
        cheque = form.save(commit=False)
        cheque.estado_cheque = 'Devolvido'
        cheque.save()
        return redirect(self.success_url)



@method_decorator(login_required(login_url='account:login'), name='dispatch')
class TodosChequesListView(ListView):
    template_name = 'cheque_list.html'
    queryset = Cheque.objects.all()


@method_decorator(login_required(login_url='account:login'), name='dispatch')
class ChequeCanceladoListView(ListView):
    template_name = 'cheque_cancelado_list.html'
    queryset = Cheque.objects.filter(estado_cheque='Cancelado')



@method_decorator(login_required(login_url='account:login'), name='dispatch')
class ChequeRegularizadoListView(ListView):
    template_name = 'cheque_regularizado_list.html'
    queryset = Cheque.objects.filter(estado_cheque='Regularizado')

def celery(request):
    update_dias.delay()
    update_status_cheque.delay()
    bloqueio_conta.delay()
    return HttpResponse('Enviado com sucesso')


@method_decorator(login_required(login_url='account:login'), name='dispatch')

class GenerateEmitentePDF(View):
    def get(self, request, *args, **kwargs):
        template = get_template('reports/emitente.html')
        queryset = Emitente.objects.all()
        context = {
            "queryset": queryset,
            "data": timezone.now()
        }
        html = template.render(context)
        pdf = render_to_pdf('reports/emitente.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Clientes_%s.pdf" %("12341231")
            content = "inline; filename='%s'" %(filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" %(filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")


@method_decorator(login_required(login_url='account:login'), name='dispatch')
class GenerateChequePDF(View):
    def get(self, request, *args, **kwargs):
        template = get_template('reports/cheque.html')
        queryset = Cheque.objects.all()
        context = {
            "queryset": queryset,
            "data": timezone.now()
        }
        html = template.render(context)
        pdf = render_to_pdf('reports/cheque.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Cheques_%s.pdf" %("12341231")
            content = "inline; filename='%s'" %(filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" %(filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")


@method_decorator(login_required(login_url='account:login'), name='dispatch')
class GenerateChequeCanceladoPDF(View):
    def get(self, request, *args, **kwargs):
        template = get_template('reports/cheque-cancelado.html')
        queryset = Cheque.objects.filter(estado_cheque='Cancelado')
        context = {
            "queryset": queryset,
            "data": timezone.now()
        }
        html = template.render(context)
        pdf = render_to_pdf('reports/cheque-cancelado.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Cheques_%s.pdf" %("12341231")
            content = "inline; filename='%s'" %(filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" %(filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")


@method_decorator(login_required(login_url='account:login'), name='dispatch')
class GenerateChequeRegularizadoPDF(View):
    def get(self, request, *args, **kwargs):
        template = get_template('reports/cheque-regularizado.html')
        queryset = Cheque.objects.filter(estado_cheque='Regularizado')
        context = {
            "queryset": queryset,
            "data": timezone.now()
        }
        html = template.render(context)
        pdf = render_to_pdf('reports/cheque-regularizado.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Cheques_%s.pdf" %("12341231")
            content = "inline; filename='%s'" %(filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" %(filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")

app/core/templates/cheque_cancelado_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<div class="container">

<h3 class="inner-tittle two">Lista de Cheques Cancelados</h3>
<div class="graph">
<div class="tables">
    <table class="table table-hover">
     <thead>
        <tr>
            <th>Numero</th>
            <th>Conta</th>
            <th>Data devolucao</th>
            <th>Valor</th>
            <th>Estado</th>
            <th>Banco</th>
        </tr>
     </thead>
     <tbody>
        <tr>
        {% for cheque in object_list  %}

            <td>{{cheque.numero_cheque}}</td>
            <td>{{cheque.numero_conta}}</td>
            <td>{{cheque.data_devolucao|date:'d-m-Y'}}</td>
            <td>{{cheque.valor_cheque}}</td>
            <td>{{cheque.estado_cheque}}</td>
            <td>{{cheque.banco.nome}}</td>
        </tr>
        {% endfor %}     
        </tbody>
      
    </table> 
</div>
<a href="{% url 'core:cheque-cancelado-relatorio' %}" class="btn btn-success">
<span class="glyphicon glyphicon-print"></span>Imprimir
</a>
</div>

</div>

{% endblock content %}

app/core/templates/cheque_create.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
 <!--/forms-inner-->
<div class="forms-inner">
<!--/set-1-->
<div class="set-1">
  <div class="graph-2 general">
    <h3 class="inner-tittle two">Registar Cheque</h3>
      <div class="grid-1">
          <div class="form-body">
            <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for field in form.visible_fields %}
              <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field|add_class:"form-control" }}
              {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
              {% endfor %}
              </div>
            {% endfor %}
            <div class="form-group">
              
              <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-ok"></span>Salvar
              </button>
              <a href="{% url 'core:index' %}" class="btn btn-danger">Cancelar</a>
              
            </div>
            
            </form> 
          </div>
        </div> 
      </div>
    </div>
  </div>
</div>
{% endblock content  %} 

app/core/templates/cheque_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<div class="container">

<h3 class="inner-tittle two">Lista de Cheques</h3>
<div class="graph">
<div class="tables">
    <table class="table table-hover">
     <thead>
        <tr>
            <th>Numero</th>
            <th>Conta</th>
            <th>Data devolucao</th>
            <th>Valor</th>
            <th>Estado</th>
            <th>Banco</th>
        </tr>
     </thead>
     <tbody>
        <tr>
        {% for cheque in object_list  %}

            <td>{{cheque.numero_cheque}}</td>
            <td>{{cheque.numero_conta}}</td>
            <td>{{cheque.data_devolucao|date:'d-m-Y'}}</td>
            <td>{{cheque.valor_cheque}}</td>
            <td>{{cheque.estado_cheque}}</td>
            <td>{{cheque.banco.nome}}</td>
        </tr>
        {% endfor %}     
        </tbody>
      
    </table> 
</div>
<a href="{% url 'core:cheque-relatorio' %}" class="btn btn-success">
<span class="glyphicon glyphicon-print"></span>Imprimir
</a>
</div>

</div>

{% endblock content %}

app/core/templates/cheque_regularizado_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<div class="container">

<h3 class="inner-tittle two">Lista de Cheques Regualrizados</h3>
<div class="graph">
<div class="tables">
    <table class="table table-hover">
     <thead>
        <tr>
            <th>Numero</th>
            <th>Conta</th>
            <th>Data devolucao</th>
            <th>Valor</th>
            <th>Estado</th>
            <th>Banco</th>
        </tr>
     </thead>
     <tbody>
        <tr>
        {% for cheque in object_list  %}

            <td>{{cheque.numero_cheque}}</td>
            <td>{{cheque.numero_conta}}</td>
            <td>{{cheque.data_devolucao|date:'d-m-Y'}}</td>
            <td>{{cheque.valor_cheque}}</td>
            <td>{{cheque.estado_cheque}}</td>
            <td>{{cheque.banco.nome}}</td>
        </tr>
        {% endfor %}     
        </tbody>
      
    </table> 
</div>
<a href="{% url 'core:cheque-regularizado-relatorio' %}" class="btn btn-success">
<span class="glyphicon glyphicon-print"></span>Imprimir
</a>
</div>

</div>

{% endblock content %}

app/core/templates/emitente_create.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
 <!--/forms-inner-->
<div class="forms-inner">
<!--/set-1-->
<div class="set-1">
  <div class="graph-2 general">
    <h3 class="inner-tittle two">Adicionar Emitente</h3>
      <div class="grid-1">
          <div class="form-body">
            <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for field in form.visible_fields %}
              <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field|add_class:"form-control" }}
              {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
              {% endfor %}
              </div>
            {% endfor %}
            <div class="form-group">
              
              <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-ok"></span>Salvar
              </button>
              <a href="{% url 'core:index' %}" class="btn btn-danger">Cancelar</a>
              
            </div>
          
            </form> 
          </div>
        </div> 
      </div>
    </div>
  </div>
</div>
{% endblock content  %} 

app/core/templates/emitente_list.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<div class="container">

<h3 class="inner-tittle two">Lista de clientes </h3>
<div class="graph">
<div class="tables">
    <table class="table table-hover">
     <thead>
        <tr>
            <th>Nome</th>
            <th>Numero da Conta</th>
            <th>Telefone</th>
            <th>Tel. Alternativo</th>
            <th>Email</th>
            <th>Endereco</th>
            <th></th>
        </tr>
     </thead>
     <tbody>
        <tr>
        
        {% for emitente in object_list  %}

            <td>{{emitente.nome}}</td>
            <td>{{emitente.numero_conta}}</td>
            <td>{{emitente.telefone_1}}</td>
            <td>{{emitente.telefone_2}}</td>
            <td>{{emitente.email}}</td>
            <td>{{emitente.endereco}}</td>
        </tr>
        {% endfor %}
        </tbody>
      
    </table> 
</div>
<a href="{% url 'core:emitente-relatorio' %}" class="btn btn-success">
<span class="glyphicon glyphicon-print"></span>Imprimir
</a>
</div>


</div>

{% endblock content %}

app/core/templates/login.html
<!DOCTYPE html>
<html>
 {% load widget_tweaks %}
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #ff5454!important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #ff5454 !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
                {% if not is_authenticated %}
					<form method="POST" action="">
						{% csrf_token %}
                        {% if form.errors %}
                     <div class="alert alert-danger alert-dismissible" role="aler">
                         <div id="form_errors">
                             {% for key,value in form.errors.items %}
                             <span class="fieldWrapper">
                                 {{ key }} : {{ value }}
                             </span>
                             {% endfor %}
                         </div>
                         <button type="button" class="close" data-dismiss="alert" aria-hidden="Close">
                             <span aria-hidden="true">&times</span>
                         </button>

                     </div>
                     {% endif %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
                             {% render_field form.username class="form-control" placeholder="Email..."  type="text" name="email" %}
							
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
                              {% render_field form.password class="form-control" placeholder="Password..." type="password" name="password" %}
						
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>
                {% endif %}
				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			
		
				<div class="mt-4">
					{% comment %} <div class="d-flex justify-content-center links">
						Nao tens uma conta? <a href="{% url 'account:register' %}" class="ml-2">Cria agora</a>
					</div> {% endcomment %}
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>